In [1]:
import pandas as pd
import numpy as np
import inspect
df = pd.DataFrame({'a': [1,2,3], 'b':[4,5,6]})
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [2]:
arr = np.arange(1,5)
# Adding scalar to array
print(arr + 5)  # [ 6  9 14 21] - 5 is broadcast to match arr's shape

# Adding arrays of different shapes
arr3 = np.array([[1], [10]])
print(arr + arr3)  # [[ 2  5 10 17] [11 14 19 26]]

[6 7 8 9]
[[ 2  3  4  5]
 [11 12 13 14]]


In [3]:
classes = inspect.getmembers(np, inspect.isclass)
dash_line = '-' * 80
chunk_size = 10
# Will print all the classes and its member funcitons
for name, cls in classes:
    print(name, cls)
    methods = [name for name, member in cls.__dict__.items() if callable(member)]
    usable_methods = [m for m in methods if m[:1] != '_']
    for i in range(0, len(usable_methods), chunk_size):
        print(usable_methods[i:i+chunk_size])
    print(dash_line)

DataSource <class 'numpy.DataSource'>
['abspath', 'exists', 'open']
--------------------------------------------------------------------------------
RankWarning <class 'numpy.RankWarning'>
--------------------------------------------------------------------------------
_CopyMode <enum '_CopyMode'>
--------------------------------------------------------------------------------
bool_ <class 'numpy.bool_'>
--------------------------------------------------------------------------------
broadcast <class 'numpy.broadcast'>
['reset']
--------------------------------------------------------------------------------
busdaycalendar <class 'numpy.busdaycalendar'>
--------------------------------------------------------------------------------
byte <class 'numpy.int8'>
['bit_count']
--------------------------------------------------------------------------------
bytes_ <class 'numpy.bytes_'>
--------------------------------------------------------------------------------
cdouble <class 'numpy.com

In [2]:
import numpy as np
# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr2d[:, 1]  # Access all rows, second column

array([2, 5])

In [5]:
arr2d = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])

In [6]:
arr2d

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [7]:
arr2d.shape  # Output: (2, 3) - 2 rows and 3 columns

(3, 4)

In [9]:
arr2d.sum(axis=0)  # Sum along the first axis (columns)
# are we adding the columns? Yes, we are summing the columns

array([12, 15, 18, 21])

In [ ]:
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

: 

In [ ]:

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")